# Generated by Django 5.0.2 on 2024-02-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_company_alter_account_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_company_admin',
            field=models.BooleanField(default=False),
        ),
    ]
