# Generated by Django 5.0.2 on 2024-02-22 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_watchlist_companies'),
        ('company', '0009_agm'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAGMInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_again', models.BooleanField(default=True)),
                ('agm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.agm')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
