# Generated by Django 5.0.2 on 2024-02-18 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_scrapped_from', models.CharField(blank=True, max_length=255, null=True)),
                ('last_traded_price', models.CharField(blank=True, max_length=255, null=True)),
                ('total_traded_quantity', models.CharField(blank=True, max_length=255, null=True)),
                ('total_trades', models.CharField(blank=True, max_length=255, null=True)),
                ('previous_day_close_price', models.CharField(blank=True, max_length=255, null=True)),
                ('high_price_low_price', models.CharField(blank=True, max_length=255, null=True)),
                ('week_high_week_low', models.CharField(blank=True, max_length=255, null=True)),
                ('open_price', models.CharField(blank=True, max_length=255, null=True)),
                ('close_price', models.CharField(blank=True, max_length=255, null=True)),
                ('total_listed_shares', models.CharField(blank=True, max_length=255, null=True)),
                ('total_paid_up_value', models.CharField(blank=True, max_length=255, null=True)),
                ('market_capitalization', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_data', to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyUrls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nepse_url', models.CharField(blank=True, max_length=255, null=True)),
                ('mero_lagani_url', models.CharField(blank=True, max_length=255, null=True)),
                ('share_sansar_url', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
