# Generated by Django 5.0.2 on 2024-02-18 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('scrapper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyurls',
            name='company',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='company.company'),
        ),
    ]
