# Generated by Django 5.0.2 on 2024-02-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_companydata_companyurls'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='primary_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='secondary_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
