# Generated by Django 5.0.2 on 2024-02-22 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_alter_companydata_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AGM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('file', models.FileField(blank=True, max_length=255, null=True, upload_to='company/agm/')),
                ('date', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
